# Generated by Django 4.2.4 on 2023-08-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='app_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
