# Generated by Django 4.2.4 on 2023-08-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userapp_app_url_alter_userapp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='qr_codes'),
        ),
    ]
