# Generated by Django 4.2.4 on 2023-08-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='app_accesses',
            field=models.ManyToManyField(blank=True, to='core.userapp'),
        ),
    ]
